resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/brooklyyounce/springboot-jsp.git
- name: cf-deploy-the-thing
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: username
    password: password
    organization: org
    space: development

jobs:
- name: job-deploy-the-thing
  serial: true
  plan:
  - {get: source-code, trigger: true}
  - task: build
    privileged: true
    file: source-code/ci/build.yml
  - put: cf-deploy-the-thing
    params:
      manifest: source-code/manifest.yml
      path: built-project/demo.jar
