resources:
- name: SpringBootSimpleRest
  type: git
  source:
    uri: https://github.com/brooklyyounce/SpringBootSimpleRest.git
- name: cf-deploy-the-thing
  type: cf
  source:
    api: https://api.run.pivotal.io
    username: younceb@goldmail.etsu.edu
    password: Brookly likes the number 47.
    organization: younceb-org
    space: development

jobs:
- name: job-deploy-the-thing
  serial: true
  plan:
  - {get: SpringBootSimpleRest, trigger: true}
  - task: build
    privileged: true
    file: SpringBootSimpleRest/ci/build.yml
  - put: cf-deploy-the-thing
    params:
      manifest: SpringBootSimpleRest/manifest.yml
      path: built-project/demo.jar

